# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: AVrC Documentation
    url: https://github.com/aponsero/AVrC_toolkit#readme
    about: Check our documentation for answers to common questions
